[package]
name = "popcorn"
version = "0.1.0"
authors = ["Hollin Wilkins <hollinrwilkins@gmail.com>"]

[dependencies]
futures = "0.1.13"
futures-cpupool = "0.1.5"

[features]
default = ["native", "cuda", "opencl"]
native = []
cuda = []
opencl = []

[workspace]
members = ["popcorn-blas"]
